import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { supabase } from './../lib/supabaseClient';
import Header from '../components/header';
const inter = Inter({ subsets: ['latin'] })
import Example from '../components/example';
export async function getServerSideProps() {
  let { data } = await supabase.from('events').select()

  return {
    props: {
      events: data
    },
  }
}

export default function Home({events}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log('events',events)}
      <Header/>
      <Example/>
    </>
  )
}
